jackal_config:
  rpc: http://host.docker.internal:51978
  grpc: custom-grpc.polkachu.com:17590
  seed_file: seed.json
  contract: jkl1customcontractaddress
networks_config:
- name: Ethereum Sepolia
  rpc: http://127.0.0.1:8545
  ws: ws://127.0.0.1:8545
  contract: 0xCustomContractAddress
  chain_id: 11155111
  finality: 2
